server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: micro1
          uri: lb://micro1
          predicates:
            - Path=/micro1/**
          filters:
            - StripPrefix=1
        - id: micro2
          uri: lb://micro2
          predicates:
            - Path=/micro2/**
        - id: micro3
          uri: lb://micro3
          predicates:
            - Path=/micro3/**
