server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: false
      discovery:
        locator:
          enabled: true
      routes:
        - id: micro1
          uri: lb://micro1
          predicates:
            - Path=/vehiculos/**
          filters:
            - StripPrefix=1
        - id: MICRO2
          uri: lb://MICRO2
          predicates:
            - Path=/reparaciones/**
          filters:
            - StripPrefix=1
        - id: MICRO3
          uri: lb://MICRO3
          predicates:
            - Path=/recibos/**
          filters:
            - StripPrefix=1
        - id: MICRO4
          uri: lb://MICRO4
          predicates:
            - Path=/reportes/**
          filters:
            - StripPrefix=1
