apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-deployment
    spec:
      containers:
        - name: autofix-gateway
          image: lilyisus/autofix_gateway:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
