apiVersion: v1
kind: PersistentVolume
metadata:
  name: ms1-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 500M
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: "/data/ms1-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms1-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 500M
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-db-deployment
  labels:
    app: ms1-db-deployment
    tier: database
spec:
  selector:
    matchLabels:
      app: ms1-db-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms1-db-deployment
        tier: database
    spec:
      containers:
      - name: ms1-db-deployment
        image: postgres
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name:  POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name:  postgres-db
                key: DB_NAME_MS1
          - name:  POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name:  postgres-credential
                key:  DB_USER
          - name:  POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  postgres-credential
                key:  DB_PASSWORD
        volumeMounts:
          - mountPath:  "/var/lib/postgresql/data"
            name:  ms1-db-data
      volumes:
        - name:  ms1-db-data
          persistentVolumeClaim:
            claimName:  ms1-db-pvc
---
kind: Service
apiVersion: v1
metadata:
  name:  ms1-db-service
  labels:
    app: ms1-db-service
    tier: database
spec:
  selector:
    app:  ms1-db-deployment
    tier: database
  type:  LoadBalancer
  ports:
  - port:  5432
    targetPort:  5432
    protocol: TCP

