apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms4-deployment
  labels:
    app: ms4-deployment
spec:
  selector:
    matchLabels:
      app: ms4-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms4-deployment
    spec:
      containers:
      - name: autofix-ms4
        image: lilyisus/autofix_ms4
        ports:
        - containerPort: 8093
